# Generated by Django 3.0.3 on 2020-06-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SciMajorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeCode', models.IntegerField(max_length=8)),
                ('collegeHistoryId', models.IntegerField(max_length=8)),
                ('province', models.CharField(max_length=16)),
                ('collegeName', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=8)),
                ('sequence', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=5)),
                ('speicaltyName', models.CharField(max_length=130)),
                ('matricGrade', models.IntegerField(max_length=5)),
                ('specialtyGradeDiff', models.IntegerField(max_length=5)),
                ('matricGradePosition', models.IntegerField(max_length=10)),
                ('positionMatricGrade', models.IntegerField(max_length=5)),
                ('averageGrade', models.IntegerField(max_length=5)),
                ('averageGradeDiff', models.IntegerField(max_length=5)),
                ('averageGradePosition', models.IntegerField(max_length=10)),
                ('positionAverageGrade', models.IntegerField(max_length=5)),
            ],
        ),
    ]
