# Generated by Django 3.0.3 on 2020-06-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artscollegeline',
            options={'ordering': ('collegeCode',), 'verbose_name': '文科调档线', 'verbose_name_plural': '文科调档线'},
        ),
        migrations.AlterModelOptions(
            name='artsenroll',
            options={'ordering': ('collegeCode',), 'verbose_name': '文科高校录取情况', 'verbose_name_plural': '文科高校录取情况'},
        ),
        migrations.AlterModelOptions(
            name='artsmajorline',
            options={'ordering': ('collegeCode',), 'verbose_name': '文科专业录取线', 'verbose_name_plural': '文科专业录取线'},
        ),
        migrations.AlterModelOptions(
            name='scienroll',
            options={'ordering': ('collegeCode',), 'verbose_name': '理科高校录取情况', 'verbose_name_plural': '理科高校录取情况'},
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='subject',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='subject',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='类别'),
        ),
    ]
