# Generated by Django 3.0.3 on 2020-06-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsMajorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeCode', models.IntegerField(max_length=8, verbose_name='学校编码')),
                ('collegeHistoryId', models.IntegerField(max_length=8)),
                ('province', models.CharField(max_length=16, verbose_name='省份')),
                ('collegeName', models.CharField(max_length=100, verbose_name='学校名称')),
                ('subject', models.CharField(max_length=8, verbose_name='类别')),
                ('sequence', models.CharField(max_length=100, verbose_name='批次')),
                ('year', models.IntegerField(max_length=5, verbose_name='年')),
                ('speicaltyName', models.CharField(max_length=130, verbose_name='专业名称')),
                ('matricGrade', models.IntegerField(max_length=5, verbose_name='实录分数')),
                ('specialtyGradeDiff', models.IntegerField(max_length=5, verbose_name='本一实录线差')),
                ('matricGradePosition', models.IntegerField(max_length=10, verbose_name='本一实录位次')),
                ('positionMatricGrade', models.IntegerField(max_length=5, verbose_name='成都二诊同位实录分')),
                ('averageGrade', models.IntegerField(max_length=5, verbose_name='平均分数')),
                ('averageGradeDiff', models.IntegerField(max_length=5, verbose_name='本一平均线差')),
                ('averageGradePosition', models.IntegerField(max_length=10, verbose_name='本一平均位次')),
                ('positionAverageGrade', models.IntegerField(max_length=5, verbose_name='成都二诊同位平均分')),
            ],
            options={
                'ordering': ('collegeCode',),
            },
        ),
        migrations.AlterModelOptions(
            name='scimajorline',
            options={'ordering': ('collegeCode',)},
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='averageGrade',
            field=models.IntegerField(max_length=5, verbose_name='平均分数'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='averageGradeDiff',
            field=models.IntegerField(max_length=5, verbose_name='本一平均线差'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='averageGradePosition',
            field=models.IntegerField(max_length=10, verbose_name='本一平均位次'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='collegeCode',
            field=models.IntegerField(max_length=8, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='collegeName',
            field=models.CharField(max_length=100, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='matricGrade',
            field=models.IntegerField(max_length=5, verbose_name='实录分数'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='matricGradePosition',
            field=models.IntegerField(max_length=10, verbose_name='本一实录位次'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='positionAverageGrade',
            field=models.IntegerField(max_length=5, verbose_name='成都二诊同位平均分'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='positionMatricGrade',
            field=models.IntegerField(max_length=5, verbose_name='成都二诊同位实录分'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='province',
            field=models.CharField(max_length=16, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='sequence',
            field=models.CharField(max_length=100, verbose_name='批次'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='specialtyGradeDiff',
            field=models.IntegerField(max_length=5, verbose_name='本一实录线差'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='speicaltyName',
            field=models.CharField(max_length=130, verbose_name='专业名称'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='subject',
            field=models.CharField(max_length=8, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='year',
            field=models.IntegerField(max_length=5, verbose_name='年'),
        ),
    ]
