# Generated by Django 3.0.3 on 2020-06-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200621_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsCollegeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeCode', models.IntegerField(max_length=8, verbose_name='学校编码')),
                ('collegeHistoryId', models.IntegerField(max_length=8)),
                ('province', models.CharField(max_length=16, verbose_name='省份')),
                ('collegeName', models.CharField(max_length=100, verbose_name='学校名称')),
                ('subject', models.CharField(max_length=8, verbose_name='类别')),
                ('sequence', models.CharField(max_length=100, verbose_name='批次')),
                ('year', models.IntegerField(max_length=5, verbose_name='年')),
                ('moveDocGrade', models.IntegerField(max_length=5, verbose_name='调档分')),
                ('averageGrade', models.IntegerField(max_length=5, verbose_name='平均分')),
                ('moveDocGradeDiff', models.IntegerField(max_length=5, verbose_name='调档本一线差')),
                ('averageGradeDiff', models.IntegerField(max_length=5, verbose_name='平均本一线差')),
                ('moveDocLocation', models.IntegerField(max_length=10, verbose_name='调档分位次')),
                ('positionMoveDocGrade', models.IntegerField(max_length=5, verbose_name='成都二诊同位调档分')),
                ('averageLocation', models.IntegerField(max_length=10, verbose_name='平均分位次')),
                ('positionAverageGrade', models.IntegerField(max_length=5, verbose_name='成都二诊同位平均分')),
            ],
            options={
                'ordering': ('collegeCode',),
            },
        ),
        migrations.CreateModel(
            name='MajorAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeCode', models.IntegerField(max_length=8, verbose_name='学校编码')),
                ('specialtyCode', models.IntegerField(max_length=10, verbose_name='专业编码')),
                ('speicaltyName', models.CharField(max_length=130, verbose_name='专业名称')),
                ('specialtyPlace', models.IntegerField(max_length=5, verbose_name='专业名次')),
                ('specialtyComment', models.CharField(max_length=5, verbose_name='专业级别')),
                ('collegeCount', models.IntegerField(max_length=6, verbose_name='开设院校数')),
                ('isKeyConstruction', models.BooleanField(verbose_name='国家特色专业')),
            ],
        ),
        migrations.CreateModel(
            name='SciCollegeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeCode', models.IntegerField(max_length=8, verbose_name='学校编码')),
                ('collegeHistoryId', models.IntegerField(max_length=8)),
                ('province', models.CharField(max_length=16, verbose_name='省份')),
                ('collegeName', models.CharField(max_length=100, verbose_name='学校名称')),
                ('subject', models.CharField(max_length=8, verbose_name='类别')),
                ('sequence', models.CharField(max_length=100, verbose_name='批次')),
                ('year', models.IntegerField(max_length=5, verbose_name='年')),
                ('moveDocGrade', models.IntegerField(max_length=5, verbose_name='调档分')),
                ('averageGrade', models.IntegerField(max_length=5, verbose_name='平均分')),
                ('moveDocGradeDiff', models.IntegerField(max_length=5, verbose_name='调档本一线差')),
                ('averageGradeDiff', models.IntegerField(max_length=5, verbose_name='平均本一线差')),
                ('moveDocLocation', models.IntegerField(max_length=10, verbose_name='调档分位次')),
                ('positionMoveDocGrade', models.IntegerField(max_length=5, verbose_name='成都二诊同位调档分')),
                ('averageLocation', models.IntegerField(max_length=10, verbose_name='平均分位次')),
                ('positionAverageGrade', models.IntegerField(max_length=5, verbose_name='成都二诊同位平均分')),
            ],
            options={
                'ordering': ('collegeCode',),
            },
        ),
    ]
