# Generated by Django 3.0.3 on 2020-06-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200623_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtYiFenYiDuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=16, null=True, verbose_name='省份')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年')),
                ('subject', models.CharField(blank=True, max_length=8, null=True, verbose_name='类别')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='人数')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
            ],
            options={
                'verbose_name': '文科一分一段',
                'verbose_name_plural': '文科一分一段',
                'ordering': ('-score',),
            },
        ),
        migrations.CreateModel(
            name='SciYiFenYiDuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(blank=True, max_length=16, null=True, verbose_name='省份')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年')),
                ('subject', models.CharField(blank=True, max_length=8, null=True, verbose_name='类别')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='人数')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='排名')),
            ],
            options={
                'verbose_name': '理科一分一段',
                'verbose_name_plural': '理科一分一段',
                'ordering': ('-score',),
            },
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='averageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均分'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='averageGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均本一线差'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='averageLocation',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均分位次'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='collegeHistoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='moveDocGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='调档分'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='moveDocGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='调档本一线差'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='moveDocLocation',
            field=models.IntegerField(blank=True, null=True, verbose_name='调档分位次'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='positionAverageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位平均分'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='positionMoveDocGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位调档分'),
        ),
        migrations.AlterField(
            model_name='artscollegeline',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='collegeHistoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='firstWishSucTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='第一志愿录取数'),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='firstWishTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='批线上第一 志愿报考数'),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='historyProYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='realRecruitTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际招生人数'),
        ),
        migrations.AlterField(
            model_name='artsenroll',
            name='secondWishSucTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='其他志愿录取数'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='averageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均分数'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='averageGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一平均线差'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='averageGradePosition',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一平均位次'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='collegeHistoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='matricGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='实录分数'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='matricGradePosition',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一实录位次'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='positionAverageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位平均分'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='positionMatricGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位实录分'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='specialtyGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一实录线差'),
        ),
        migrations.AlterField(
            model_name='artsmajorline',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='majorability',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='majorability',
            name='collegeCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='开设院校数'),
        ),
        migrations.AlterField(
            model_name='majorability',
            name='specialtyCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='专业编码'),
        ),
        migrations.AlterField(
            model_name='majorability',
            name='specialtyPlace',
            field=models.IntegerField(blank=True, null=True, verbose_name='专业名次'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='averageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均分'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='averageGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均本一线差'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='averageLocation',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均分位次'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='collegeHistoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='moveDocGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='调档分'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='moveDocGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='调档本一线差'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='moveDocLocation',
            field=models.IntegerField(blank=True, null=True, verbose_name='调档分位次'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='positionAverageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位平均分'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='positionMoveDocGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位调档分'),
        ),
        migrations.AlterField(
            model_name='scicollegeline',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='collegeHistoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='firstWishSucTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='第一志愿录取数'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='firstWishTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='批线上第一 志愿报考数'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='historyProYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='realRecruitTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际招生人数'),
        ),
        migrations.AlterField(
            model_name='scienroll',
            name='secondWishSucTotal',
            field=models.IntegerField(blank=True, null=True, verbose_name='其他志愿录取数'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='averageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='平均分数'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='averageGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一平均线差'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='averageGradePosition',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一平均位次'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='collegeCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='学校编码'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='collegeHistoryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='matricGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='实录分数'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='matricGradePosition',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一实录位次'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='positionAverageGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位平均分'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='positionMatricGrade',
            field=models.IntegerField(blank=True, null=True, verbose_name='成都二诊同位实录分'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='specialtyGradeDiff',
            field=models.IntegerField(blank=True, null=True, verbose_name='本一实录线差'),
        ),
        migrations.AlterField(
            model_name='scimajorline',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年'),
        ),
    ]
