# Generated by Django 3.0.3 on 2020-06-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200626_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('parentId', models.IntegerField(verbose_name='父节点')),
            ],
            options={
                'verbose_name': '录取批次',
                'verbose_name_plural': '录取批次',
            },
        ),
    ]
