# Generated by Django 3.0.3 on 2020-06-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='majorability',
            options={'ordering': ('collegeCode',), 'verbose_name': '专业实力', 'verbose_name_plural': '专业实力'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': '录取批次', 'verbose_name_plural': '录取批次'},
        ),
    ]
