# Generated by Django 3.0.3 on 2020-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_enrollmentgulde'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speicaltyName', models.CharField(blank=True, max_length=32, null=True, verbose_name='专业名称')),
                ('categoryName', models.CharField(max_length=16, verbose_name='类别')),
                ('parentCategoryName', models.CharField(max_length=8, verbose_name='父级类别')),
                ('graduateScale', models.CharField(blank=True, max_length=16, null=True, verbose_name='毕业生规模')),
                ('employInterval', models.CharField(blank=True, max_length=4, null=True, verbose_name='就业区间')),
                ('specialtyLevelName', models.CharField(blank=True, max_length=2, null=True, verbose_name='本/专')),
            ],
        ),
    ]
