# Generated by Django 3.0.3 on 2020-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_majorinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorinfo',
            options={'verbose_name': '专业库', 'verbose_name_plural': '专业库'},
        ),
        migrations.AlterField(
            model_name='majorinfo',
            name='parentCategoryName',
            field=models.CharField(max_length=16, verbose_name='父级类别'),
        ),
    ]
