# Generated by Django 3.0.3 on 2020-07-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20200709_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorability',
            name='collegeName',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='学校名称'),
        ),
        migrations.AddField(
            model_name='majorability',
            name='specialtyLevelName',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='本/专'),
        ),
    ]
