"""
Django settings for GkWeb project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r=f4o6779a2k!9zz5(5tre5=e^-w#-qo-b+6j)u+3^dj9vpfbv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #配置跨域问题中间件
    'web.utils.middlewares.CorsMiddlewarse'
]

ROOT_URLCONF = 'GkWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GkWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gk_db',
        'USER': 'root',
        'PASSWORD': 'toor',
        'HOST': '121.37.162.150',
        # 'HOST': '127.0.0.1',
        'PORT': '3307',
        # 'HOST': '116.63.170.14',
        # 'PORT': '3307',
        }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#配置reids 缓存
CACHES = {
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://:toor@121.37.162.150:6379/1",
        # "LOCATION":"redis://:toor@127.0.0.1:6379/1",
        # "LOCATION":"redis://116.63.170.14:6379/1",
        # "LOCATION":"redis://:toor@192.168.10.120:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
#redis的timeout
REDIS_TIMEOUT=7*24*60*60
CUBES_REDIS_TIMEOUT=60*60
NEVER_REDIS_TIMEOUT=365*24*60*60
#redis的key

#学校信息列表
REDIS_COLLEGEINFO = 'collegeinfo'
#理科调档线
REDIS_SCICOLLEGELINE = 'scicollegeline'   #这里面存储的是经过group by后的结果
REDIS_ALLSCICOLLEGELINE = 'allscicollegeline'  #这里面存储原始结果
#文科调档线
REDIS_ARTSCOLLEGELINE = 'artscollegeline'              #这里面存储的是经过group by后的结果
REDIS_ALLARTSCOLLEGELINE = 'allartscollegeline'        #这里面存储原始结果
#理科招生计划
REDIS_SCIPLAN = 'sciplan'
#文科招生计划
REDIS_ARTSPLAN = 'artsplan'


#配置限速
# REST_FRAMEWORK = {
#     #限速设置
#     'DEFAULT_THROTTLE_CLASSES': (
#             'rest_framework.throttling.AnonRateThrottle',   # 未登陆用户
#             'rest_framework.throttling.UserRateThrottle'    # 登陆用户
#         ),
#     'DEFAULT_THROTTLE_RATES': {
#         'anon': '3/minute',         # 每分钟可以请求两次
#         'user': '5/minute'          # 每分钟可以请求五次
#     }
# }


#配置默认主题
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

#配置simpleui为中文
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False # 这里务必调整为False，否则时区设置无效

#关闭首页的几个信息显示模块
SIMPLEUI_HOME_INFO = False
# SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_ANALYSIS = False


SIMPLEUI_CONFIG = {
    'system_keep': False, # 关闭系统菜单
    # 'menu_display': ['专业录取线', '测试', '权限认证'],
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'app': 'myapp',
        'name': '认证与授权',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': '/admin/auth/user/'
        },{
            'name': '组',
            'icon': 'fa fa-user',
            'url': '/admin/auth/group/'
        }]
    },{
        'app': 'myapp',
        'name': '专业录取线',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科录取线',
            'icon': 'fa fa-user',
            'url': '/admin/web/scimajorline/'
        },{
            'name': '文科录取线',
            'icon': 'fa fa-user',
            'url': '/admin/web/artsmajorline/'
        }]
    },{
        'app': 'myapp',
        'name': '调档线',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科调档线',
            'icon': 'fa fa-user',
            'url': '/admin/web/scicollegeline/'
        },{
            'name': '文科调档线',
            'icon': 'fa fa-user',
            'url': '/admin/web/artscollegeline/'
        }]
    },{
        'app': 'myapp',
        'name': '学校信息',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '学校信息',
            'icon': 'fa fa-user',
            'url': '/admin/web/collegeinfo/'
        },{
            'name': '招生简章',
            'icon': 'fa fa-user',
            'url': '/admin/web/enrollmentgulde/'
        },{
            'name': '专业实力',
            'icon': 'fa fa-user',
            'url': '/admin/web/majorability/'
        },{
            'name': '专业库',
            'icon': 'fa fa-user',
            'url': '/admin/web/majorinfo/'
        },{
            'name': '录取批次',
            'icon': 'fa fa-user',
            'url': '/admin/web/order/'
        },{
            'name': '省份',
            'icon': 'fa fa-user',
            'url': '/admin/web/province/'
        }]
    },{
        'app': 'myapp',
        'name': '录取情况',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科录取情况',
            'icon': 'fa fa-user',
            'url': '/admin/web/scienroll/'
        },{
            'name': '文科录取情况',
            'icon': 'fa fa-user',
            'url': '/admin/web/artsenroll/'
        }]
    },{
        'app': 'myapp',
        'name': '招生计划',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科招生计划',
            'icon': 'fa fa-user',
            'url': '/admin/web/sciplan/'
        },{
            'name': '文科招生计划',
            'icon': 'fa fa-user',
            'url': '/admin/web/artsplan/'
        }]
    },{
        'app': 'myapp',
        'name': '系统管理',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': '/admin/web/user/'
        }]
    }]
}