"""
Django settings for GkWeb project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r=f4o6779a2k!9zz5(5tre5=e^-w#-qo-b+6j)u+3^dj9vpfbv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'web.apps.WebConfig',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GkWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GkWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gk_db',
        'USER': 'root',
        'PASSWORD': 'toor',
        'HOST': '192.168.10.120',
        'PORT': '3306',
        }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

#配置默认主题
SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'

#配置simpleui为中文
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False # 这里务必调整为False，否则时区设置无效

#关闭首页的几个信息显示模块
SIMPLEUI_HOME_INFO = False
# SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False
SIMPLEUI_ANALYSIS = False


SIMPLEUI_CONFIG = {
    'system_keep': False, # 关闭系统菜单
    # 'menu_display': ['专业录取线', '测试', '权限认证'],
    'dynamic': True,    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [{
        'app': 'myapp',
        'name': '认证与授权',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '用户',
            'icon': 'fa fa-user',
            'url': '/admin/auth/user/'
        },{
            'name': '组',
            'icon': 'fa fa-user',
            'url': '/admin/auth/group/'
        }]
    },{
        'app': 'myapp',
        'name': '专业录取线',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科录取线',
            'icon': 'fa fa-user',
            'url': '/admin/web/scimajorline/'
        },{
            'name': '文科录取线',
            'icon': 'fa fa-user',
            'url': '/admin/web/artsmajorline/'
        }]
    },{
        'app': 'myapp',
        'name': '调档线',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科调档线',
            'icon': 'fa fa-user',
            'url': '/admin/web/scicollegeline/'
        },{
            'name': '文科调档线',
            'icon': 'fa fa-user',
            'url': '/admin/web/artscollegeline/'
        }]
    },{
        'app': 'myapp',
        'name': '学校信息',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '学校信息',
            'icon': 'fa fa-user',
            'url': '/admin/web/collegeinfo/'
        },{
            'name': '专业实力',
            'icon': 'fa fa-user',
            'url': '/admin/web/majorability/'
        }]
    },{
        'app': 'myapp',
        'name': '录取情况',
        'icon': 'fas fa-user-shield',
        'models': [{
            'name': '理科录取情况',
            'icon': 'fa fa-user',
            'url': '/admin/web/scienroll/'
        },{
            'name': '文科录取情况',
            'icon': 'fa fa-user',
            'url': '/admin/web/artsenroll/'
        }]
    }]
}